name: Push to branch

on:
    push:
      branches:
        - release

jobs:
        install:
            name: Installing Packages
            runs-on: ubuntu-latest
            steps:
                - name: Checkout
                  uses: actions/checkout@v3

                - name: Cache node_modules
                  uses: actions/cache@v2
                  with:
                    path: node_modules
                    key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
                        
                - name: Install Dependencies
                  run: npm install


        testing:
            name: Run unit test
            runs-on: ubuntu-latest
            needs: install
            steps:
                - name: Checkout
                  uses: actions/checkout@v3
        
                - name: Restore node_modules
                  uses: actions/cache@v2
                  with:
                    path: node_modules
                    key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
                                
                - name: Run tests
                  run: npm run test  

        
        security:
            name: Run snyk test
            runs-on: ubuntu-latest
            needs: install
            steps:               
                - uses: actions/checkout@master
                - name: Run Snyk to test for vulnerabilities
                  uses: snyk/actions/node@master
                  env:
                    SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
                  with:
                    args: --severity-threshold=high
                  
                  
        securitytest:
            name: Run security test
            runs-on: ubuntu-latest
            needs: install
            steps:
                - name: Checkout
                  uses: actions/checkout@v3
                
                - name: Restore node_modules
                  uses: actions/cache@v2
                  with:
                    path: node_modules
                    key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
                                        
                - name: Run security tests
                  run: npm run snyk
                  
                
